version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 8081:3306
    volumes:
      - ./respaldo:/home/respaldo
    environment:
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: qpwoeiru
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: qpwoeiru
  web:
    image: wordpress:5.4.2
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes/
      - ./wp-content/plugins:/var/www/html/wp-content/plugins/
      - ./wp-content/uploads:/var/www/html/wp-content/uploads/

    environment:
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=qpwoeiru
      - WORDPRESS_DB_HOST=mysql
    ports:
      - 8088:80

volumes:
  data:
